"""empty message

Revision ID: bd798a6fce5f
Revises: 65dd81fc61d8
Create Date: 2024-02-14 12:29:31.773974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd798a6fce5f'
down_revision = '65dd81fc61d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_effects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quality_name', sa.String(), nullable=True),
    sa.Column('ambush', sa.Integer(), nullable=True),
    sa.Column('outwit', sa.Integer(), nullable=True),
    sa.Column('overpower', sa.Integer(), nullable=True),
    sa.Column('convince', sa.Integer(), nullable=True),
    sa.Column('extort', sa.Integer(), nullable=True),
    sa.Column('bribe', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_effects')),
    sa.UniqueConstraint('quality_name', name=op.f('uq_action_effects_quality_name'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('action_effects')
    # ### end Alembic commands ###
