"""empty message

Revision ID: c603e396e4e4
Revises: f02a3f43f81d
Create Date: 2024-02-14 17:24:10.323273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c603e396e4e4'
down_revision = 'f02a3f43f81d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_teams_team_name'), ['team_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_teams_team_name'), type_='unique')

    # ### end Alembic commands ###
