"""empty message

Revision ID: f02a3f43f81d
Revises: bd798a6fce5f
Create Date: 2024-02-14 16:29:50.100632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f02a3f43f81d'
down_revision = 'bd798a6fce5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classification_json', sa.Text(), nullable=True))
        batch_op.drop_column('classification')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classification', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('classification_json')

    # ### end Alembic commands ###
